routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('questions', 'QuestionsController')->except('show'); //because we dont want slug in show method instead of question-id


/**
 * All routes of questions takes question-id in their routes if needed  and then they provide it to QuestionsController an object of Question,
 * But when we want to use slug, routes have slug but we want object of Question in QuestionsController so we first process this slug and get corresponding Question Object and then return it to the QuestionsController.
 * For that we have to first register it in the routeprovider.
 */

Route::get('questions/{slug}', 'QuestionsController@show')->name('questions.show'); //for route binding of this we have to add code in provider:
Route::resource('questions.answers', 'AnswersController')->except(['index', 'show', 'create']);
Route::put('answers/{answer}/best-answer', 'AnswersController@bestAnswer')->name('answers.bestAnswer');


Route::post('questions/{question}/favorite', 'FavoritesController@store')->name('questions.favorite');
Route::delete('questions/{question}/unfavorite', 'FavoritesController@destroy')->name('questions.unfavorite');


//routes for votes-questions:
Route::post('questions/{question}/vote/{vote}', 'VotesController@voteQuestion')->name('questions.vote');
Route::post('answers/{answer}/vote/{vote}', 'VotesController@voteAnswer')->name('answers.vote');


Route::get('users/notifications', 'UsersController@notifications')->name('users.notifications');

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    //
    protected $fillable = [
        'body',
        'user_id'
    ];


    public function  getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }
    public function getBestAnswerStatusAttribute()
    {
        if ($this->id === $this->question->best_answer_id) {
            return "text-success";
        }
        return "text-dark";
    }
    public function getIsBestAttribute()
    {
        return $this->id === $this->question->best_answer_id;
    }




    /********************************************************************REGISTERING THE EVENTS**************************************************************/

    //WE DONOT HAVE TO DO ANYTHING TO REGISTER EVENTS OF THE MODEL, ONLY WE HAVE TO REGISTER HERE:
    public static function boot()
    {
        parent::boot();

        /**
         * This function wil invoke callback function when instance of Answer class is created so we can incremenet the answers_count of that question in questions table.
         */
        static::created(function ($answer) {
            $answer->question->increment('answers_count');
        });

        /**
         * This function will be called when instance of Answer class is deleted so that we can decremenet the answers count.
         */
        static::deleted(function ($answer) {
            $answer->question->decrement('answers_count');
        });
    }

    /*******************************************************************END REGISTERING THE EVENTS**************************************************************/




    /********************************************************************RELATIONSHIP FUNCTIONS**************************************************************/

    public function question()
    {
        return $this->belongsTo(Question::class);
    }
    public function author()
    {
        return $this->belongsTo(User::class, 'user_id'); //Second argument is 'foreign-key' we have to specify here because by default it will take functionname_id but foreign key is not author_id , forign key is 'user_id' we can make the function name as user then we dont need to map the forign key it will then take automatically.
    }
    public function votes()
    {
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }

    /********************************************************************RELATIONSHIP FUNCTIONS**************************************************************/

    public function vote(int $vote)
    {
        //insert the record in the bridging table:
        $this->votes()->attach(auth()->id(), ['vote' => $vote]);

        //add or subtract the count into the votes_count of question table:
        if ($vote < 0) {
            $this->decrement('votes_count');
        } else {
            $this->increment('votes_count');
        }
    }


    /**
     * This function is used to update the user vote (for example: votes_count = 10 of questions table  and user already up-voted and now down voting so question is down voted by 2  and vice versa for already down-voted and now up-voting so question is upvoted by 2 (1 for user undo his action and 1 for he is upvoting ))
     *
     * @param integer $vote
     * @return void
     */
    public function updateVote(int $vote)
    {
        //update the record:
        $this->votes()->updateExistingPivot(auth()->id(), ['vote' => $vote]); //updateExistingPivot() is used when we want to update the column of bridging table except from user_id and vote_id.
        if ($vote < 0) {
            $this->decrement('votes_count');
            $this->decrement('votes_count');
        } else {
            $this->increment('votes_count');
            $this->increment('votes_count');
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /******************************************ACCESSORS**************************************************************/

    /**
     * Accessors are the functions which are used to get the attributes without () , we can access them as a property:
     */
    public function getAvatarAttribute()
    {
        $size = 40;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}";
    }
    /*******************************************END OF ACCESSORS**************************************************************/



    /****************************************RELATIONSHIP FUCNCTIONS**************************************************************/


    /**
     * This function is relationship function to get all questions of this user
     *
     * @return Reationship
     */
    public function questions()
    {
        return $this->hasMany(Question::class);
    }

    /**
     * This function is used to get all the answers of this user
     *
     * @return Relationship
     */
    public function answers()
    {
        return $this->hasMany(Answer::class);
    }


    public function favorites()
    {
        return $this->belongsToMany(Question::class)->withTimestamps();
    }


    //polymorphics many to many relationship:
    public function votesQuestions()
    {
        return $this->morphedByMany(Question::class, 'vote')->withTimestamps();
    }
    public function votesAnswers()
    {
        return $this->morphedByMany(Answer::class, 'vote')->withTimestamps();
    }



    /******************************************END OF RELATIONSHIP FUCNCTIONS**************************************************************/

    /****************************************HELPER FUCNCTIONS**************************************************************/
    public function hasQuestionUpVote(Question $question)
    {
        return auth()->user()->votesQuestions()->where(['vote' => 1, 'vote_id' => $question->id])->exists();
    }

    public function hasQuestionDownVote(Question $question)
    {
        return auth()->user()->votesQuestions()->where(['vote' => -1, 'vote_id' => $question->id])->exists();
    }
    public  function hasVoteForQuestion(Question $question)
    {
        return $this->hasQuestionUpVote($question) || $this->hasQuestionDownVote($question);
    }



    public function hasAnswerUpVote(Answer $answer)
    {
        return auth()->user()->votesAnswers()->where(['vote' => 1, 'vote_id' => $answer->id])->exists();
    }

    public function hasAnswerDownVote(Answer $answer)
    {
        return auth()->user()->votesAnswers()->where(['vote' => -1, 'vote_id' => $answer->id])->exists();
    }
    public  function hasVoteForAnswer   (Answer $answer)
    {
        return $this->hasAnswerUpVote($answer) || $this->hasAnswerDownVote($answer);
    }



    /****************************************END HELPER FUCNCTIONS**************************************************************/
}

app/Http/Controllers/AnswersController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use Illuminate\Http\Request;
use App\Question;
use App\Http\Requests\answers\CreateAnswerRequest;
use App\Http\Requests\answers\UpdateAnswerRequest;
use App\Notifications\NewReplyAdded;

class AnswersController extends Controller
{

    public function store(CreateAnswerRequest $request, Question $question)
    {
        //
        $question->answers()->create([
            'body' => $request->body,
            'user_id' => auth()->id()
        ]);
        $question->owner->notify(new NewReplyAdded($question));
        session()->flash('success', 'Your Answer has ben submitted successfully!');
        return redirect($question->url);
    }

    public function edit(Question $question, Answer $answer)
    {
        //
        return view('answers.edit', compact([
            'answer',
            'question'
        ]));
    }

    public function update(UpdateAnswerRequest $request, Question $question, Answer $answer)
    {
        //
        $answer->update([
            'body' => $request->body,
        ]);

        session()->flash('success', 'Answer Updated Successfully');
        return redirect($question->url);
    }


    public function destroy(Question $question, Answer $answer)
    {
        //
        $this->authorize('delete', $answer);
        $answer->delete();
        session()->flash('success', 'answer has been deleted successfuly!');
        return redirect(route('questions.index'));
    }

    public function bestAnswer(Answer $answer)
    {
        $this->authorize('markAsBest', $answer);
        if ($answer->question->best_answer_id === $answer->id) {
            $answer->question->undoBestAnswer();
            session()->flash('success', 'Answer has been unmarked Best');
            return redirect($answer->question->url);
        }

        $answer->question->markBestAnswer($answer);
        session()->flash('success', 'Answer has been marked Best');
        return redirect($answer->question->url);
    }
}

resources/views/answers/_create.blade.php
<div class="row mt-5">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3>Your Answer</h3>
            </div>
            <div class="card-body">
                <form action="{{ route('questions.answers.store',$question->id) }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <input id="body" type="hidden" name="body" value="{{ old('body') }}">
                        <trix-editor input="body"></trix-editor>
                        @error('body')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-outline-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/answers/_index.blade.php
<!--This view has all answers,  and this view is included in the show view of questions --->

<div class="row-mt-4">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3 class="mt-0">
                    {{ Str::plural('Answer', $question->answers_count) }}
                </h3>
            </div>

            <div class="card-body">
                @forelse($question->answers as $answer)
                <div class="answer-container d-flex">
                    <!--Answer Stats -->
                    <div class="answer-status d-flex flex-column">
                        @can('vote',$answer)

                                        <form action="{{route('answers.vote',[$answer->id, 1])}}" method="POST">
                                            @csrf
                                            <button type="submit" class="btn {{auth()->user()->hasanswerUpVote($answer) ? 'text-dark' : 'text-black-50'}}">
                                                <i class="fa fa-caret-up fa-3x" aria-hidden="true"></i>
                                            </button>
                                        </form>

                                    @else
                                    <a href="{{route('login')}}" title="Up Vote" class="vote-up d-block text=black-50">

                                    </a>
                                    @endcan
                                     <h4 class="votes-count text-muted text-center m-0">{{$answer->votes_count}}</h4>

                                     @can('vote',$answer)

                                        <form action="{{route('answers.vote',[$answer->id, -1])}}" method="POST">
                                            @csrf
                                            <button type="submit" class="btn {{auth()->user()->hasAnswerDownVote($answer) ? 'text-dark' : 'text-black-50'}}">
                                                <i class="fa fa-caret-down fa-3x" aria-hidden="true"></i>
                                            </button>
                                        </form>

                                    @else
                                    <a href="{{route('login')}}" title="down Vote" class="vote-down d-block text=black-50">

                                    </a>
                                    @endcan

                        <div class="mt-2">
                        @can('markAsBest',$answer)
                            <form action="{{route('answers.bestAnswer',$answer->id)}}" method="POST">
                            @csrf
                            @method('PUT')

                                <button type="submit" class="btn {{ $answer->best_answer_status }}"><i class="fa fa-check fa-2x"></i></button>
                            </form>
                            @else
                                @if($answer->isBest)
                                    <i class="fa fa-check fa-2x d-block text-success mb-2"></i>
                                @endif
                        @endcan

                    </div>
                    </div>
                    <!-- End Answer Stats -->

                    <!-- Answer Content -->
                    <div class="answer-content w-100">
                            {!! $answer->body !!}

                    <div class="d-flex justify-content-between">
                        <div>
                            <div class="d-flex">
                                @can('update',$answer)
                                <a href="{{ route('questions.answers.edit',[$question->id, $answer->id]) }}" class="btn btn-sm btn-primary">Edit</a>
                                @endcan


                                @can('delete',$answer)
                                    <form action="{{route('questions.answers.destroy',[$question->id,$answer->id])}}" method="POST">
                                    @csrf
                                    @method('DELETE')

                                    <button type="submit" onclick="return confirm('Are you sure u want to delete the post');" class="btn ml-3 btn-danger">Delete</button>
                                    </form>
                                @endcan
                            </div>
                        </div>
                        <div class="d-flex flex-column">
                            <div class="text-muted mb-2 text-right">
                                Answered {{ $answer->created_date }}
                            </div>
                            <div class="d-flex mb-2">
                                <div>
                                    <img src="{{$answer->author->avatar}}" alt="">
                                </div>
                                <div class="mt-2 ml-2">
                                    {{$answer->author->name}}
                                </div>
                            </div>
                        </div>
                    </div>
                 </div>
            </div>


                <hr>
                @empty
                    <h1>No Answers</h1>
                @endforelse
            </div>
        </div>
    </div>
</div>

resources/views/answers/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="row mt-5">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3>Your Answer</h3>
            </div>
            <div class="card-body">
                <form action="{{ route('questions.answers.update', [$question->id,$answer->id]) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <input id="body" type="hidden" name="body" value="{{ old('body', $answer->body) }}">
                        <trix-editor input="body"></trix-editor>
                        @error('body')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-outline-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection



@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
@endsection

@section('styles')
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
@endsection