routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('questions', 'QuestionsController')->except('show'); //because we dont want slug in show method instead of question-id


/**
 * All routes of questions takes question-id in their routes if needed  and then they provide it to QuestionsController an object of Question,
 * But when we want to use slug, routes have slug but we want object of Question in QuestionsController so we first process this slug and get corresponding Question Object and then return it to the QuestionsController.
 * For that we have to first register it in the routeprovider.
 */

Route::get('questions/{slug}', 'QuestionsController@show')->name('questions.show'); //for route binding of this we have to add code in provider:
Route::resource('questions.answers', 'AnswersController')->except(['index', 'show', 'create']);
Route::put('answers/{answer}/best-answer', 'AnswersController@bestAnswer')->name('answers.bestAnswer');


Route::post('questions/{question}/favorite', 'FavoritesController@store')->name('questions.favorite');
Route::delete('questions/{question}/unfavorite', 'FavoritesController@destroy')->name('questions.unfavorite');


//routes for votes-questions:
Route::post('questions/{question}/vote/{vote}', 'VotesController@voteQuestion')->name('questions.vote');
Route::post('answers/{answer}/vote/{vote}', 'VotesController@voteAnswer')->name('answers.vote');


Route::get('users/notifications', 'UsersController@notifications')->name('users.notifications');

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Question extends Model
{
    //
    protected $guarded = [];


    /*****************************************************ACCESSORS**************************************************************/

    public function getUrlAttribute() //this function in invoked whenever we hit $question->url. (currently we are using thsi function to give a single-post's link)
    {
        return "questions/{$this->slug}";
    }


    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    /**
     * This function is used to check the conditions of the answer (if the answer is answered,unanswered or is_best_answer) and return the style according to it.
     *
     * @return void
     */
    public function getAnswersStyleAttribute()
    {
        if ($this->answers_count > 0) {
            if ($this->best_answer_id) {
                return "has-best-answer";
            }
            return "answered";
        }
        return "unanswered";
    }


    /**
     * This function retuns the favorites count of this question.
     *
     * @return int
     */
    public function getFavoritesCountAttribute()
    {
        return $this->favorites->count();
    }


    /**
     * This function returns true if this question is favorite for loggedin user
     *
     * @return boolean
     */
    public function getIsFavoriteAttribute()
    {
        return $this->favorites()->where(['user_id' => auth()->id()])->count() > 0;
    }
    /******************************************************END OF ACCESSORS**************************************************************/






    /*************************************************************MUTATORS**************************************************************/


    /**
     * MUTATORS: These are special functions which have set***Attribute($value)
     * It is a magic fuction which invoked whenever we set attribute associated with this function:
     * for:Eg if we set setNameAttribute($value) then this function will be called whenever we set Name.
     */

    /**
     * This function is invoked whenever we set the value of title, at that time we will also make the slug from title and store both of them into $this=>attributes array.
     *
     * @param [type] $title
     * @return void
     */
    public function setTitleAttribute($title)
    {

        $this->attributes['title'] = $title;
        $this->attributes['slug'] = Str::slug($title);
    }


    /******************************************************END OF MUTATORS**************************************************************/





    /******************************************************RELATIONSHIP FUNCTIONS DEFINATION**************************************************************/


    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id'); //here we have to specify the foreign key otherwise it will take function name as foreign key: for example it consider forign key as (owner) but our foreign key name is 'user_id' so we have mentioned

    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function favorites()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }


    //polymorphic many to many relationship

    public function votes()
    {
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }
    /******************************************************END OF RELATIONSHIP FUNCTIONS DEFINATION**************************************************************/




    /********************************************************************HELPER FUNCTIONS**************************************************************/

    public function undoBestAnswer()
    {
        $this->best_answer_id = null;
        $this->save();
    }

    public function markBestAnswer(Answer $answer)
    {
        $this->best_answer_id = $answer->id;
        $this->save();
    }

    /**
     * This function is invoked when user first time upvote or down vote for creating new record of user_id and question_id
     *
     * @param integer $vote
     * @return void
     */
    public function vote(int $vote)
    {
        //insert the record in the bridging table:
        $this->votes()->attach(auth()->id(), ['vote' => $vote]);

        //add or subtract the count into the votes_count of question table:
        if ($vote < 0) {
            $this->decrement('votes_count');
        } else {
            $this->increment('votes_count');
        }
    }


    /**
     * This function is used to update the user vote (for example: votes_count = 10 of questions table  and user already up-voted and now down voting so question is down voted by 2  and vice versa for already down-voted and now up-voting so question is upvoted by 2 (1 for user undo his action and 1 for he is upvoting ))
     *
     * @param integer $vote
     * @return void
     */
    public function updateVote(int $vote)
    {
        //update the record:
        $this->votes()->updateExistingPivot(auth()->id(), ['vote' => $vote]); //updateExistingPivot() is used when we want to update the column of bridging table except from user_id and vote_id.
        if ($vote < 0) {
            $this->decrement('votes_count');
            $this->decrement('votes_count');
        } else {
            $this->increment('votes_count');
            $this->increment('votes_count');
        }
    }


    /********************************************************************END OF HELPER FUNCTIONS**************************************************************/
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /******************************************ACCESSORS**************************************************************/

    /**
     * Accessors are the functions which are used to get the attributes without () , we can access them as a property:
     */
    public function getAvatarAttribute()
    {
        $size = 40;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}";
    }
    /*******************************************END OF ACCESSORS**************************************************************/



    /****************************************RELATIONSHIP FUCNCTIONS**************************************************************/


    /**
     * This function is relationship function to get all questions of this user
     *
     * @return Reationship
     */
    public function questions()
    {
        return $this->hasMany(Question::class);
    }

    /**
     * This function is used to get all the answers of this user
     *
     * @return Relationship
     */
    public function answers()
    {
        return $this->hasMany(Answer::class);
    }


    public function favorites()
    {
        return $this->belongsToMany(Question::class)->withTimestamps();
    }


    //polymorphics many to many relationship:
    public function votesQuestions()
    {
        return $this->morphedByMany(Question::class, 'vote')->withTimestamps();
    }
    public function votesAnswers()
    {
        return $this->morphedByMany(Answer::class, 'vote')->withTimestamps();
    }



    /******************************************END OF RELATIONSHIP FUCNCTIONS**************************************************************/

    /****************************************HELPER FUCNCTIONS**************************************************************/
    public function hasQuestionUpVote(Question $question)
    {
        return auth()->user()->votesQuestions()->where(['vote' => 1, 'vote_id' => $question->id])->exists();
    }

    public function hasQuestionDownVote(Question $question)
    {
        return auth()->user()->votesQuestions()->where(['vote' => -1, 'vote_id' => $question->id])->exists();
    }
    public  function hasVoteForQuestion(Question $question)
    {
        return $this->hasQuestionUpVote($question) || $this->hasQuestionDownVote($question);
    }



    public function hasAnswerUpVote(Answer $answer)
    {
        return auth()->user()->votesAnswers()->where(['vote' => 1, 'vote_id' => $answer->id])->exists();
    }

    public function hasAnswerDownVote(Answer $answer)
    {
        return auth()->user()->votesAnswers()->where(['vote' => -1, 'vote_id' => $answer->id])->exists();
    }
    public  function hasVoteForAnswer   (Answer $answer)
    {
        return $this->hasAnswerUpVote($answer) || $this->hasAnswerDownVote($answer);
    }



    /****************************************END HELPER FUCNCTIONS**************************************************************/
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use App\Http\Requests\questions\CreateQuestion;
use Illuminate\Support\Facades\Gate;


use Illuminate\Http\Request;

class QuestionsController extends Controller
{

    public function __Construct()
    {
        $this->middleware(['auth'])->only(['create', 'store']);
    }

    public function index()
    {

        $questions = Question::with('owner')
            ->latest()
            ->paginate(10);

        return view('questions.index', compact([
            'questions',
        ]));
    }

    public function create()
    {
        //
        app('debugbar')->disable();
        return view('questions.create');
    }

    public function store(Request $request)
    {
        //
        auth()->user()->questions()->create([
            'title' => $request->title,
            'body' => $request->body
        ]);
        session()->flash('success', "Question has been added successfully");
        return redirect(route('questions.index'));
    }

    public function show(Question $question)
    {
        //
        $question->increment('views_count');
        return view('questions.show', compact([
            'question'
        ]));
    }

    public function edit(Question $question)
    {

        // if (Gate::allows('update-question', $question)) {

        if ($this->authorize('update', $question)) {
            return view('questions.edit', compact([
                'question',
            ]));
        }

        // }


        abort(403);
    }


    public function update(Request $request, Question $question)
    {


        // if (Gate::allows('update-question', $question)) {

        if ($this->authorize('update', $question)) {
            $question->update([
                'title' => request('title'),
                'body' => $request->body
            ]);
            session()->flash('success', "Question has been Updated successfully");
            return redirect(route('questions.index'));
        }

        // }
        abort(403);
    }

    public function destroy(Question $question)
    {
        //
        // if (auth()->user()->can('delete-question', $question)) {
        // above if is used with gates now i am commenting it because i have used policies here:
        if ($this->authorize('delete', $question)) {
            $question->delete();
            session()->flash('success', "Question has been successfully deleted!");
            return redirect(route('questions.index'));
        }


        // }
        abort(403);
    }
}

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><h3>Ask a Question</h3></div>
                <div class="card-body">
                <form action={{ route('questions.store') }} method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text"
                        id="title"
                        name="title"
                        placeholder="Enter Title"
                        value="{{ old('title') }}"
                        class="form-control @error('title') is-invalid : '' @enderror">
                        @error('title')
                             <div class="text-danger">{{$message}}</div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <input id="body" type="hidden" name="body" value="{{old('body')}}">
                        <trix-editor input="body"></trix-editor>
                        @error('body')
                            <div class="danger">{{$message}}</div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-outline-success">Post a Question!</button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
@endsection

@section('styles')
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><h3>Update Question</h3></div>
                <div class="card-body">
                <form action={{ route('questions.update',$question->id) }} method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text"
                        id="title"
                        name="title"
                        placeholder="Enter Title"
                        value="{{ old('title',$question->title) }}"
                        class="form-control @error('title') is-invalid : '' @enderror">
                        @error('title')
                             <div class="text-danger">{{$message}}</div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <input id="body" type="hidden" name="body" value="{{old('body',$question->body)}}">
                        <trix-editor input="body"></trix-editor>
                        @error('body')
                            <div class="danger">{{$message}}</div>
                        @enderror
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-outline-success">Upadate Question!</button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
@endsection

@section('styles')
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app');

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    All Questions
                <a href="{{route('questions.create')}}" class="btn btn-sm btn-primary">Add Question</a>
                </div>
                @foreach($questions as $question)
                    <div class="card-body">
                        <div class="media">
                            <div class="d-flex flex-column statistics">

                                <div class="votes text-center mb-3">
                                <strong class="d-block">{{$question->votes_count}}</strong>
                                    Votes
                                </div>

                                <div class="answers text-center mb-3">
                                <strong class="d-block answers {{$question->answers_style}}">{{$question->answers_count}}</strong>
                                    Answers
                                </div>

                                <div class="views text-center">
                                <strong class="d-block">{{$question->views_count}}</strong>
                                Views
                                </div>

                            </div>

                            <div class="media-body">

                                <div class="d-flex justify-content-between">
                                    <h4>
                                        <a href="{{ $question->url }}">{{$question->title}}</a>
                                    </h4>

                                    <div class="d-flex justify-content-between">

                            <!---------------------------------------------------------To Apply Gates Below Code----------------------------------------------------->

                                                    <!-- If u want to use can() method using if of php so u have to call like below -->

                                                    {{-- @if(auth()>user() && auth()->user()->can('update-post'),$question) <!-- CODE GOES HERE --> @endif --}}

                                                     {{-- If u want to use @can method of blade u have to call like below  --}}

                                                    {{-- @can('update-question',$question)) <!--CODE GOES HERE --> @endcan--}}


                                                <!------------------------------------1-method---USING GATES CODE -------------using if---------------->

                                            @if(auth()->user() && auth()->user()->can('update-post',$question))
                                                <div class="mr-2">
                                                     <a href=" {{route('questions.edit',$question->id)}} " class="btn btn-sm btn-outline-primary">Edit</a>
                                                </div>
                                            @endif



                                                    <!------------------------------------2-method---USING GATES CODE -------------using can---------------->

                                            @can('update-question',$question)
                                                <div class="mr-2">
                                                <a href=" {{route('questions.edit',$question->id)}} " class="btn btn-sm btn-outline-primary">Edit</a>
                                            </div>
                                            @endcan

                            <!---------------------------------------------------------To Apply Gates Below Code----------------------------------------------------->

                                            <!-- for using policy we have to hit the command (php artisan make:policy policy_name --model="model_name") -->
                                            <!-- This will create the policy class in the App/policy/policy_name
                                            inside this call we have already craeted methods same as controller
                                            we have to just over-ride the methods and return true or false depending uson teh condition
                                            After writing condition we have to register it in App/provide/auth-provider -->


                                            @can('update',$question)
                                                <div class="mr-2">
                                                    <a href=" {{route('questions.edit',$question->id)}} " class="btn btn-sm btn-outline-primary">Edit</a>
                                                </div>

                                            @endcan



                                        @can('delete',$question)

                                            <form action="{{route('questions.destroy',$question->id)}}" method="POST">
                                                @csrf()
                                                @method('DELETE')
                                                <button type ="submit" onclick="return confirm('Are you sure you want to delete?');"class="btn btn-sm btn-outline-danger">Delete</button>
                                            </form>

                                        @endcan


                                    </div>

                                </div>
                                <p>
                                    Asked By: <a href="">{{$question->owner->name}}</a>
                                    <span class="text-muted">Asked: {{$question->created_date}}</span>
                                </p>
                                <p>
                                    {!! Str::limit($question->title,255) !!}
                                </p>
                            </div>
                        </div>
                    </div>
                    <hr>
                    @endforeach
                <div class="card-footer">
                    {{$questions->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')



@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h1>{{ $question->title }}</h1>
                    </div>
                    <div class="card-body">
                        {!! $question->body !!}
                    </div>
                    <div class="card-footer">
                        <div class="d-flex justify-content-between mr-3">
                            <div class="d-flex">
                                <div>
                                    @can('vote',$question)

                                        <form action="{{route('questions.vote',[$question->id, 1])}}" method="POST">
                                            @csrf
                                            <button type="submit" class="btn {{auth()->user()->hasQuestionUpVote($question) ? 'text-dark' : 'text-black-50'}}">
                                                <i class="fa fa-caret-up fa-3x" aria-hidden="true"></i>
                                            </button>
                                        </form>

                                    @else
                                    <a href="{{route('login')}}" title="Up Vote" class="vote-up d-block text=black-50">

                                    </a>
                                    @endcan
                                     <h4 class="votes-count text-muted text-center m-0">{{$question->votes_count}}</h4>

                                     @can('vote',$question)

                                        <form action="{{route('questions.vote',[$question->id, -1])}}" method="POST">
                                            @csrf
                                            <button type="submit" class="btn {{auth()->user()->hasQuestionDownVote($question) ? 'text-dark' : 'text-black-50'}}">
                                                <i class="fa fa-caret-down fa-3x" aria-hidden="true"></i>
                                            </button>
                                        </form>

                                    @else
                                    <a href="{{route('login')}}" title="down Vote" class="vote-down d-block text=black-50">

                                    </a>
                                    @endcan

                                </div>

                                <div class="ml-5 mt-2 {{$question->is_favorite ? 'text-warning' : 'text-black-50'}}">
                                        @can('markAsFavorite',$question)
                                        <form action="{{route($question->is_favorite ? 'questions.unfavorite' : 'questions.favorite', $question->id)}}" method="POST">
                                        @csrf
                                        @if($question->is_favorite)
                                            @method('DELETE')
                                        @endif
                                            <button type="submit" class="btn {{$question->is_favorite ? 'text-warning' : 'text-black-50'}}">
                                            <i class="fa {{$question->is_favorite ? 'fa-star' : 'fa-star-o'}} fa-2x"></i>
                                            </button>
                                        </form>
                                        <h4 class="votes-count m-0 text-center">{{$question->favorites_count}}</h4>
                                        @else

                                        <i class="fa fa-star-o fa-2x" aria-hidden="true"></i>
                                        <h4 class="votes-count m-0 text-center">{{$question->favorites_count}}</h4>

                                    @endcan


                                </div>
                            </div>
                            <div class="d-flex flex-column">
                                <div class="text-muted mb-2 text-right">
                                    Asked {{ $question->created_date }}
                                </div>
                                <div class="d-flex mb-2">
                                    <div>
                                        <img src="{{ $question->owner->avatar }}" alt="">
                                    </div>
                                    <div class="mt-2 ml-2">
                                        {{ $question->owner->name }}
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--ANSWERS-->
        @include('answers._index')
        @include('answers._create')
    </div>
@endsection


@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
@endsection

@section('styles')
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.css">
@endsection